server:
  port: 8081

logging:
  pattern:
    level: "%5p [${spring.application.name},%X{traceId:-},%X{spanId:-}]"

log:
  app-name: scheduler-service

management:
  endpoints:
    web:
      exposure:
        include: "*"