server:
  port: 8080

spring:
  application:
    name: mycaprio-service
  datasource:
    url: jdbc:postgresql://45.127.6.252:5432/mycaprio
    username: '{cipher}07e34b915564c52bf6fe3fe82e047fe04c8e32a3537ec17be0241b1aa0089a6b'
    password: '{cipher}0993f541031bfbf60e9e605d4b46f3fa4996ef42bb5e52daf54d571cb028225d'
    rewriteBatchedStatements: true
    testWhileIdle: true
    validationQuery: SELECT 1
    hikari:
      connectionTimeout: 50000
      maxLifetime: 60000
      data-source-properties:
        cachePrepStmts: true
        useServerPrepStmts: true
        rewriteBatchedStatements: true
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: create
    database-platform: org.hibernate.dialect.PostgreSQLDialect

logging:
  pattern:
    level: "%5p [${spring.application.name},%X{traceId:-},%X{spanId:-}]"

log:
  app-name: mycaprio-service

token:
  secretKey: '{cipher}dc788bed3a6ddb50a1f0e2b4fc411b8af2b12a117ac7d175f80884dbf71feb4e288716750d95946967e3c15ed36b8ac4f668a057179330088f6eeba2cbd4f5ce49b7273bddcc7c963e37d8fc3aa082f39cfa2278560d024934e9e774e21689f1'
  accessTokenExpiration: 86400000 # a day
  refreshTokenExpiration: 604800000 # 7 days

management:
  endpoints:
    web:
      exposure:
        include: "*"