package org.everowl.mycaprio.shared.exception;

import lombok.Getter;
import org.everowl.mycaprio.shared.enums.ErrorCode;

/**
 * Custom exception class for representing IO-related errors.
 * Extends RuntimeException to allow unchecked throwing.
 */
@Getter
public class IOException extends RuntimeException {
    /**
     * The specific error code associated with this exception.
     */
    private final ErrorCode errorCode;

    /**
     * Additional result data related to the exception.
     */
    private Object result;

    /**
     * Constructs an IOException with the specified error code.
     *
     * @param errorCode The ErrorCode enum value representing the specific IO error.
     */
    public IOException(ErrorCode errorCode) {
        super(errorCode.getMessage());
        this.errorCode = errorCode;
    }

    /**
     * Constructs an IOException with the specified error code and additional result data.
     *
     * @param errorCode The ErrorCode enum value representing the specific IO error.
     * @param result Additional data related to the IO error.
     */
    public IOException(ErrorCode errorCode, Object result) {
        super(errorCode.getMessage());
        this.errorCode = errorCode;
        this.result = result;
    }

    // Note: Getter methods for errorCode and result are automatically generated by Lombok's @Getter annotation
}
