package org.everowl.mycaprio.shared.exception;

import lombok.Getter;
import org.everowl.mycaprio.shared.enums.ErrorCode;

/**
 * Custom exception class for representing runtime errors.
 * Extends RuntimeException to allow unchecked throwing.
 * Note: This class name might be confused with the standard Java RuntimeException.
 * Consider renaming to avoid potential confusion.
 */
@Getter
public class RunTimeException extends RuntimeException {
    /**
     * The specific error code associated with this exception.
     */
    private final ErrorCode errorCode;

    /**
     * Additional result data related to the exception.
     */
    private Object result;

    /**
     * Constructs a RunTimeException with the specified error code.
     *
     * @param errorCode The ErrorCode enum value representing the specific runtime error.
     */
    public RunTimeException(ErrorCode errorCode) {
        super(errorCode.getMessage());
        this.errorCode = errorCode;
    }

    /**
     * Constructs a RunTimeException with the specified error code and additional result data.
     *
     * @param errorCode The ErrorCode enum value representing the specific runtime error.
     * @param result    Additional data related to the runtime error.
     */
    public RunTimeException(ErrorCode errorCode, Object result) {
        super(errorCode.getMessage());
        this.errorCode = errorCode;
        this.result = result;
    }

    // Note: Getter methods for errorCode and result are automatically generated by Lombok's @Getter annotation
}