package org.everowl.shared.service.exception;

import lombok.Getter;
import org.everowl.shared.service.enums.ErrorCode;

/**
 * Custom exception class for representing forbidden access scenarios.
 * Extends RuntimeException to allow unchecked throwing.
 */
@Getter
public class ForbiddenException extends RuntimeException {
    private final ErrorCode errorCode;
    private Object result;

    /**
     * Constructs a ForbiddenException with the specified error code.
     *
     * @param errorCode The ErrorCode enum value representing the specific forbidden error.
     */
    public ForbiddenException(ErrorCode errorCode) {
        super(errorCode.getMessage());
        this.errorCode = errorCode;
    }

    /**
     * Constructs a ForbiddenException with the specified error code and additional result data.
     *
     * @param errorCode The ErrorCode enum value representing the specific forbidden error.
     * @param result    Additional data related to the forbidden access scenario.
     */
    public ForbiddenException(ErrorCode errorCode, Object result) {
        super(errorCode.getMessage());
        this.errorCode = errorCode;
        this.result = result;
    }

    // Note: Getter methods for errorCode and result are automatically generated by Lombok's @Getter annotation
}