package org.everowl.shared.service.exception;

import lombok.Getter;
import org.everowl.shared.service.enums.ErrorCode;

/**
 * Custom exception class for representing authorization-related errors.
 * Extends RuntimeException to allow unchecked throwing.
 */
@Getter
public class NotAuthorizedException extends RuntimeException {
    /**
     * The specific error code associated with this exception.
     */
    private final ErrorCode errorCode;

    /**
     * Additional result data related to the exception.
     */
    private Object result;

    /**
     * Constructs a NotAuthorizedException with the specified error code.
     *
     * @param errorCode The ErrorCode enum value representing the specific authorization error.
     */
    public NotAuthorizedException(ErrorCode errorCode) {
        super(errorCode.getMessage());
        this.errorCode = errorCode;
    }

    /**
     * Constructs a NotAuthorizedException with the specified error code and additional result data.
     *
     * @param errorCode The ErrorCode enum value representing the specific authorization error.
     * @param result    Additional data related to the authorization error.
     */
    public NotAuthorizedException(ErrorCode errorCode, Object result) {
        super(errorCode.getMessage());
        this.errorCode = errorCode;
        this.result = result;
    }

    // Note: Getter methods for errorCode and result are automatically generated by Lombok's @Getter annotation
}